### ISSUE TITLE
Umbrella 1.0

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/inline-style-prefixer#66]
- [x] default to `prefixAll` if userAgent can't be parsed
- [x] use [inline-style-prefix-all](https://github.com/rofrischmann/inline-style-prefix-all) for `prefixAll`
- [x] remove userAgent warning (which gets resolved by the first task)
- [x] update caniuse data
- [x] update docs
- [x] fix #63 ( https://github.com/Khan/inline-style-prefixer/commit/f41f3040ac27eeec3b7a1fb7450ddce250cac4e4 )

**Comment by harumando** [comment]
https://github.com/rofrischmann/inline-style-prefixer/issues/40
Hello, is there any solution for this bug yet? I have the same error and i'm getting warning in the console that my user agent is not supported by inline-style-prefixer.
Thank you.
